import 'package:flutter/material.dart';

import 'session_storage.dart';

class LanguageProvider extends ChangeNotifier {
  LanguageProvider({SessionStorage? sessionStorage})
    : _sessionStorage = sessionStorage ?? SessionStorage() {
    hydrate();
  }

  final SessionStorage _sessionStorage;
  Locale _locale = const Locale('en');

  Locale get locale => _locale;
  bool get isRTL => _locale.languageCode == 'ar';
  String get languageCode => _locale.languageCode;

  Future<void> hydrate() async {
    final stored = await _sessionStorage.readLanguage();
    if (stored != null && stored.isNotEmpty) {
      _locale = Locale(stored);
      notifyListeners();
    }
  }

  Future<void> setLanguage(String code) async {
    _locale = Locale(code);
    await _sessionStorage.saveLanguage(code);
    notifyListeners();
  }

  String t(String key) {
    final language = _locale.languageCode;
    return _translations[language]?[key] ?? _translations['en']?[key] ?? key;
  }
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.loading': 'Loading...',
    'common.or': 'or',
    'common.retry': 'Retry',
    'units.feddan': 'Feddan',
    'units.celsius': '°C',
    'units.percent': '%',
    'units.kmh': 'km/h',
    'app.name': 'AgriLens',
    'app.tagline': 'Smart Farming Assistant',
    'onboarding.title1': 'Detect Plant Diseases',
    'onboarding.desc1':
        'Take a photo of your plant and get AI-powered disease detection.',
    'onboarding.title2': 'Track Your Fields',
    'onboarding.desc2':
        'Monitor field health, risks, and history in one place.',
    'onboarding.title3': 'Get Actionable Advice',
    'onboarding.desc3':
        'Use AgriBot for prevention tips and result explanations.',
    'onboarding.skip': 'Skip',
    'onboarding.getStarted': 'Get Started',
    'language.title': 'Choose Your Language',
    'language.subtitle': 'Select your preferred language',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.continue': 'Continue',
    'login.title': 'Welcome Back!',
    'login.subtitle': 'Enter your phone number to continue',
    'login.phone': 'Phone Number',
    'login.phonePlaceholder': '01234567890',
    'login.sendOTP': 'Send Code',
    'login.otpTitle': 'Enter Verification Code',
    'login.otpSubtitle': 'We sent a code to',
    'login.verify': 'Verify',
    'login.resend': 'Resend Code',
    'login.successTitle': 'Welcome!',
    'login.successMessage': 'You are now logged in',
    'home.goodMorning': 'Good morning',
    'home.goodAfternoon': 'Good afternoon',
    'home.goodEvening': 'Good evening',
    'home.goodNight': 'Good night',
    'home.farmer': 'Farmer',
    'home.plantHealth': "Today's Plant Health",
    'home.healthyStatus': 'Healthy status across your fields',
    'home.quickScan': 'Quick Scan',
    'home.quickScanDesc': 'Detect diseases instantly',
    'home.activeAlerts': 'Active Alerts',
    'home.alerts': 'Alerts',
    'home.viewAll': 'View All',
    'home.moderateRisk': 'Moderate risk detected',
    'home.treatmentComplete': 'Treatment completed',
    'home.weatherToday': 'Weather Today',
    'home.partlyCloudy': 'Partly Cloudy',
    'home.humidity': 'Humidity',
    'home.wind': 'Wind',
    'home.temp': 'Temp',
    'home.myFields': 'My Fields',
    'home.forecasting': 'Forecasting',
    'fields.title': 'My Fields',
    'fields.viewMap': 'View Map',
    'fields.addNew': 'Add New Field',
    'fields.healthy': 'Healthy',
    'fields.warning': 'Warning',
    'fields.area': 'Area',
    'fields.healthScore': 'Health Score',
    'fields.overview': 'Overview',
    'fields.totalArea': 'Total Area',
    'fields.avgHealth': 'Avg Health',
    'fields.riskDetected': 'moderate risk areas detected',
    'fields.fieldName': 'Field A',
    'fields.location': 'Location',
    'fields.cropType': 'Crop Type',
    'fields.soilType': 'Soil Type',
    'fields.irrigationType': 'Irrigation Type',
    'fields.editField': 'Edit Field',
    'fields.riskLevel': 'Risk Level',
    'fields.health': 'Health',
    'fields.alerts': 'Alerts',
    'fields.totalFields': 'Total Fields',
    'map.title': 'Disease Map',
    'map.statusLegend': 'Risk Legend',
    'map.lowRiskDescription': 'Stable health or low disease risk',
    'map.mediumRiskDescription': 'Needs attention or a fresh scan',
    'map.highRiskDescription': 'Urgent action recommended',
    'map.summary': 'Summary',
    'map.needsMonitoring': 'Needs monitoring',
    'map.highRiskFields': 'High risk fields',
    'map.noCoordinatesTitle': 'No map coordinates available',
    'map.noCoordinatesMessage':
        'Add latitude and longitude to a field to show it on the map.',
    'map.noCoordinatesHint':
        'Open Add Field or Edit Field, then enter the field coordinates.',
    'map.openFieldDetails': 'Tap a marker to open field details',
    'addField.title': 'Add New Field',
    'addField.editTitle': 'Edit Field',
    'addField.infoBanner':
        'Register your field to enable disease monitoring and forecasting.',
    'addField.editInfoBanner':
        'Update your field information to keep monitoring data accurate.',
    'addField.name': 'Field Name',
    'addField.namePlaceholder': 'e.g., Field A, North Farm',
    'addField.location': 'Location',
    'addField.locationPlaceholder': 'e.g., North Section, Village Name',
    'addField.markOnMap': 'Mark on map',
    'addField.area': 'Area (Feddan)',
    'addField.areaPlaceholder': 'e.g., 2.5',
    'addField.cropType': 'Crop Type',
    'addField.selectCrop': 'Select crop type',
    'addField.soilType': 'Soil Type',
    'addField.selectSoil': 'Select soil type',
    'addField.irrigation': 'Irrigation System',
    'addField.selectIrrigation': 'Select irrigation type',
    'addField.photo': 'Field Photo (Optional)',
    'addField.takePhoto': 'Take or upload photo',
    'addField.updatePhoto': 'Update photo',
    'addField.submit': 'Add Field',
    'addField.update': 'Save Changes',
    'addField.successTitle': 'Field Added Successfully!',
    'addField.successMessage': 'Your new field has been registered',
    'addField.updateSuccessTitle': 'Field Updated Successfully!',
    'addField.updateSuccessMessage': 'Your changes have been saved',
    'addField.deleteTitle': 'Delete Field?',
    'addField.deleteMessage':
        'This action cannot be undone. All field data will be permanently removed.',
    'addField.confirmDelete': 'Yes, Delete Field',
    'addField.required': 'Required',
    'crops.rice': 'Rice',
    'crops.corn': 'Corn',
    'crops.tomato': 'Tomato',
    'crops.tomatoes': 'Tomatoes',
    'crops.potato': 'Potato',
    'crops.potatoes': 'Potatoes',
    'crops.apple': 'Apple',
    'crops.apples': 'Apples',
    'crops.grape': 'Grape',
    'crops.wheat': 'Wheat',
    'crops.mushroom': 'Mushroom',
    'crops.sugarCane': 'Sugar Cane',
    'crops.sweetPotato': 'Sweet Potato',
    'crops.cotton': 'Cotton',
    'crops.onion': 'Onion',
    'crops.onions': 'Onions',
    'crops.cucumber': 'Cucumber',
    'crops.pepper': 'Pepper',
    'crops.eggplant': 'Eggplant',
    'crops.bean': 'Bean',
    'crops.beans': 'Beans',
    'crops.barley': 'Barley',
    'crops.other': 'Other',
    'soil.clay': 'Clay',
    'soil.sandy': 'Sandy',
    'soil.loamy': 'Loamy',
    'soil.silty': 'Silty',
    'soil.peaty': 'Peaty',
    'soil.chalky': 'Chalky',
    'irrigation.drip': 'Drip Irrigation',
    'irrigation.sprinkler': 'Sprinkler',
    'irrigation.surface': 'Surface/Flood',
    'irrigation.manual': 'Manual',
    'irrigation.rainfed': 'Rain-fed',
    'scan.title': 'Scan Plant',
    'scan.instruction': 'Point camera at affected leaf or plant',
    'scan.tips': 'Tips for best results:',
    'scan.tip1': 'Use good lighting',
    'scan.tip2': 'Get close to the leaf',
    'scan.tip3': 'Keep camera steady',
    'scan.tip4': 'Focus on affected area',
    'scan.capture': 'Capture Photo',
    'scan.gallery': 'Choose from Gallery',
    'scan.analyzing': 'Analyzing plant...',
    'scan.photoMode': 'Photo Mode',
    'scan.videoMode': 'Video Mode',
    'scan.videoInstruction': 'Record video of affected plant areas',
    'scan.videoTip': 'Max 30 seconds - Show multiple angles',
    'scan.resultTitle': 'Detection Result',
    'scan.confidence': 'Confidence',
    'scan.severity': 'Severity',
    'scan.viewDetails': 'View Full Details',
    'scan.scanAnother': 'Scan Another Plant',
    'scan.saveToField': 'Save to Field',
    'scan.selectCrop': 'Select Your Crop',
    'scan.selectCropDesc':
        'Choose the crop you want to scan for better accuracy',
    'scan.comingSoon': 'Coming soon',
    'scan.cropComingSoon':
        '{crop} scanning is coming soon. You can still add it to fields.',
    'scan.noResults': 'No disease detected',
    'scan.healthy': 'Plant appears healthy',
    'disease.overview': 'Overview',
    'disease.symptoms': 'Symptoms',
    'disease.treatment': 'Treatment',
    'disease.prevention': 'Prevention',
    'disease.affectedArea': 'Affected Area',
    'disease.detectionDate': 'Detection Date',
    'disease.recommendedAction': 'Recommended Action',
    'disease.urgency': 'Urgency',
    'disease.high': 'High',
    'disease.medium': 'Medium',
    'disease.low': 'Low',
    'chat.title': 'AgriBot Assistant',
    'chat.subtitle': 'Always here to help',
    'chat.placeholder': 'Ask me anything...',
    'chat.greeting': "Hello! I'm AgriBot. How can I help you today?",
    'chat.tryAsking': 'Try asking:',
    'chat.question1': 'What diseases affect tomatoes?',
    'chat.question2': 'How to prevent leaf blight?',
    'chat.question3': 'Best fertilizer for wheat?',
    'chat.question4': 'When to water crops?',
    'chat.buttonTooltip': 'Chat with AgriBot',
    'forecast.title': 'Disease Forecasting',
    'forecast.currentRisk': 'Current Risk Level',
    'forecast.riskTrend': '7-Day Risk Trend',
    'forecast.lowRisk': 'Low Risk',
    'forecast.moderateRisk': 'Moderate Risk',
    'forecast.highRisk': 'High Risk',
    'forecast.weatherImpact': 'Weather Impact',
    'forecast.favorableConditions': 'Favorable conditions for disease spread',
    'forecast.upcomingAlerts': 'Upcoming Alerts',
    'reports.title': 'Reports',
    'reports.generate': 'Generate New Report',
    'reports.monthly': 'Monthly Summary',
    'reports.seasonal': 'Seasonal Analysis',
    'reports.download': 'Download PDF',
    'reports.share': 'Share Report',
    'reports.noReports': 'No reports yet',
    'reports.createFirst': 'Generate your first report to see insights',
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.today': 'Today',
    'notifications.yesterday': 'Yesterday',
    'notifications.earlier': 'Earlier',
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.accountSettings': 'Account Settings',
    'profile.subscription': 'Subscription Plan',
    'profile.helpSupport': 'Help & Support',
    'profile.about': 'About AgriLens',
    'profile.logout': 'Log Out',
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.editProfile': 'Edit Profile',
    'settings.phoneNumber': 'Phone Number',
    'settings.email': 'Email Address',
    'settings.preferences': 'Preferences',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.units': 'Units',
    'settings.privacy': 'Privacy & Security',
    'settings.changePassword': 'Change Password',
    'settings.dataPrivacy': 'Data Privacy',
    'settings.termsConditions': 'Terms & Conditions',
    'settings.help': 'Help & Support',
    'settings.tutorial': 'App Tutorial',
    'settings.contactSupport': 'Contact Support',
    'settings.faq': 'FAQ',
    'subscription.title': 'Subscription',
    'subscription.currentPlan': 'Current Plan',
    'subscription.upgrade': 'Upgrade Plan',
    'subscription.free': 'Free Plan',
    'subscription.basic': 'Basic Plan',
    'subscription.standard': 'Standard Plan',
    'subscription.premium': 'Premium Plan',
    'subscription.choosePlan': 'Choose Your Plan',
    'subscription.month': '/month',
    'subscription.selectPlan': 'Select Plan',
    'subscription.confirmPayment': 'Confirm Payment',
    'subscription.paymentMethod': 'Payment Method',
    'subscription.success': 'Subscription Activated!',
    'subscription.current': 'Current Plan',
    'subscription.pro': 'Pro Plan',
    'subscription.enterprise': 'Enterprise Plan',
    'subscription.cardNumber': 'Card Number',
    'subscription.expiry': 'Expiry Date',
    'subscription.cvv': 'CVV',
    'subscription.pay': 'Pay Now',
    'subscription.confirmTitle': 'Payment Successful!',
    'subscription.confirmMessage':
        'Your subscription has been activated successfully.',
    'subscription.manage': 'Manage Subscription',
    'subscription.cancelPlan': 'Cancel Plan',
    'subscription.renewDate': 'Renewal Date',
    'subscription.usage': 'Usage This Month',
    'subscription.trialActive': 'Free Trial',
    'subscription.trialDaysLeft': 'days left in your free trial',
    'subscription.trialExpiredTitle': 'Free Trial Ended',
    'subscription.trialExpiredBody': 'Your 1-week free trial has ended. Choose a plan to continue using AgriLens.',
    'subscription.choosePlanBtn': 'Choose a Plan',
    'subscription.payment': 'Payment',
    'subscription.orderSummary': 'Order Summary',
    'subscription.total': 'Total',
    'subscription.selectPayment': 'Select Payment Method',
    'subscription.card': 'Credit / Debit Card',
    'subscription.vodafoneCash': 'Vodafone Cash',
    'subscription.fawry': 'Fawry',
    'subscription.instaPay': 'InstaPay',
    'subscription.holderName': 'Card Holder Name',
    'subscription.mobileNumber': 'Mobile Number',
    'subscription.fawryCode': 'Your Fawry Reference Code',
    'subscription.bankName': 'Select Bank',
    'subscription.accountNumber': 'Account / IBAN Number',
    'subscription.processing': 'Processing Payment...',
    'subscription.receiptSent': 'A receipt has been sent to your registered phone number.',
    'nav.home': 'Home',
    'nav.scan': 'Scan',
    'nav.fields': 'Fields',
    'nav.forum': 'Forum',
    'nav.reports': 'Reports',
    'nav.profile': 'Profile',
    'registration.title': 'Create Your Profile',
    'registration.subtitle': 'Tell us a bit about yourself',
    'registration.fullName': 'Full Name',
    'registration.namePlaceholder': 'Enter your full name',
    'registration.country': 'Country',
    'registration.selectCountry': 'Select your country',
    'registration.egypt': 'Egypt',
    'registration.saudiArabia': 'Saudi Arabia',
    'registration.uae': 'UAE',
    'registration.jordan': 'Jordan',
    'registration.profilePhoto': 'Profile Photo (Optional)',
    'registration.uploadPhoto': 'Upload Photo',
    'registration.changePhoto': 'Change Photo',
    'registration.continue': 'Continue',
    'editProfile.title': 'Edit Profile',
    'editProfile.subtitle': 'Update your information',
    'editProfile.name': 'Full Name',
    'editProfile.email': 'Email Address',
    'editProfile.emailPlaceholder': 'your@email.com',
    'editProfile.phone': 'Phone Number',
    'editProfile.country': 'Country',
    'editProfile.photo': 'Profile Photo',
    'editProfile.saveChanges': 'Save Changes',
    'editProfile.successTitle': 'Profile Updated!',
    'editProfile.successMessage': 'Your profile has been updated successfully',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions',
    'faq.q1': 'How does disease detection work?',
    'faq.a1':
        'AgriLens analyzes plant images, estimates the most likely disease, and returns confidence, severity, and guidance.',
    'faq.q2': 'How accurate is the disease detection?',
    'faq.a2':
        'Accuracy depends on crop coverage and image quality. Use the confidence score and confirm critical cases with an agronomist.',
    'faq.q3': 'Can I use AgriLens offline?',
    'faq.a3':
        'The app can queue scans locally. Detection and synced results appear when connectivity returns.',
    'faq.q4': 'What crops does AgriLens support?',
    'faq.a4':
        'This release focuses on tomato, corn, wheat, and sweet potato scans, with more crops planned as new models are added.',
    'faq.q5': 'How do I add multiple fields?',
    'faq.a5':
        'Go to My Fields, tap Add New Field, and enter the field details.',
    'faq.q6': 'What does forecasting show?',
    'faq.a6':
        'Forecasting combines recent detections and weather conditions to estimate short-term disease risk.',
    'terms.title': 'Terms & Conditions',
    'terms.subtitle': 'Last updated: March 2026',
    'privacy.title': 'Data Privacy Policy',
    'privacy.subtitle': 'How we protect your information',
    'support.title': 'Contact Support',
    'support.subtitle': "We're here to help",
    'support.email': 'Email Us',
    'support.emailAddress': 'support@agrilens.app',
    'support.phone': 'Call Us',
    'support.phoneNumber': '+20 123 456 7890',
    'support.hours': 'Support Hours',
    'support.hoursTime': 'Sunday - Thursday: 9 AM - 6 PM',
    'support.sendMessage': 'Send a Message',
    'support.name': 'Your Name',
    'support.emailLabel': 'Your Email',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.messagePlaceholder': 'Describe your issue or question...',
    'support.submit': 'Send Message',
    'support.successTitle': 'Message Sent!',
    'support.successMessage': "We'll respond within 24 hours",
    'tutorial.title': 'App Tutorial',
    'tutorial.subtitle': 'Learn how to use AgriLens',
    'tutorial.step1Title': 'Scan Plants',
    'tutorial.step1':
        'Capture a clear image of the affected part of the plant.',
    'tutorial.step2Title': 'View Results',
    'tutorial.step2':
        'Review disease prediction, confidence, severity, and recommendations.',
    'tutorial.step3Title': 'Manage Fields',
    'tutorial.step3':
        'Add your fields and keep their crop and irrigation details updated.',
    'tutorial.step4Title': 'Check Forecasts',
    'tutorial.step4':
        'View short-term disease risk based on recent scans and weather.',
    'tutorial.step5Title': 'Review Reports',
    'tutorial.step5':
        'Generate reports for scan history and field monitoring activity.',
    'tutorial.step6Title': 'Ask AgriBot',
    'tutorial.step6':
        'Use the assistant for quick explanations and prevention tips.',
    'tutorial.watchVideo': 'Watch Video Tutorial',
    'tutorial.restart': 'Restart Tutorial',
    'privacy.intro': 'Your privacy matters to us. AgriLens collects only what is necessary to deliver disease detection, field monitoring, and reports. We never sell your data.',
    'privacy.section1Title': 'What We Collect',
    'privacy.section1': 'We collect plant images you upload, scan results, field details (name, location, crop type), and basic usage patterns. No personal financial data is ever collected.',
    'privacy.section2Title': 'How We Use Your Data',
    'privacy.section2': 'Your data powers AI disease detection, field health reports, and forecasting. Aggregated, anonymized patterns may be used to improve model accuracy over time.',
    'privacy.section3Title': 'Data Storage & Security',
    'privacy.section3': 'All data is encrypted in transit (TLS) and at rest. Images are stored on secured servers. Access is restricted to authorised AgriLens systems only.',
    'privacy.section4Title': 'Your Rights',
    'privacy.section4': 'You may view, export, or permanently delete your data at any time via Account Settings or by contacting support@agrilens.app. We will action requests within 7 days.',
    'privacy.section5Title': 'Third-Party Sharing',
    'privacy.section5': 'We do not sell or rent your data. We share data only with trusted service providers (cloud hosting, analytics) under strict data-processing agreements.',
    'privacy.section6Title': 'Contact & Updates',
    'privacy.section6': 'For any privacy concern, email support@agrilens.app. We may update this policy periodically; continued use of the app constitutes acceptance of changes.',
    'terms.intro': 'Please read these terms carefully before using AgriLens. By creating an account or using the app you agree to be bound by them.',
    'terms.section1Title': 'Acceptance of Terms',
    'terms.section1': 'By accessing or using AgriLens you confirm that you are at least 18 years old and agree to these Terms & Conditions. If you disagree with any part, please stop using the app.',
    'terms.section2Title': 'Use of the Service',
    'terms.section2': 'AgriLens is provided for agricultural monitoring and plant disease detection. You agree not to misuse the service, reverse-engineer the app, or attempt to access systems without authorisation.',
    'terms.section3Title': 'Disease Detection Disclaimer',
    'terms.section3': 'All detection results are AI-powered estimates based on image analysis and are not a substitute for professional agronomic advice. Always consult a qualified specialist for critical or high-stakes decisions.',
    'terms.section4Title': 'Account & Data Responsibility',
    'terms.section4': 'You are responsible for keeping your login credentials secure and for all activity under your account. Notify us immediately at support@agrilens.app if you suspect unauthorised access.',
    'terms.section5Title': 'Intellectual Property',
    'terms.section5': 'All AI models, designs, trademarks, and software in AgriLens are owned by or licensed to AgriLens. Unauthorised copying, distribution, or commercial use is strictly prohibited.',
    'terms.section6Title': 'Changes & Termination',
    'terms.section6': 'We may update these terms or suspend accounts that violate them at any time. Continued use of the app after a policy update constitutes your acceptance of the new terms.',
  },
  'ar': {
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.done': 'تم',
    'common.loading': 'جاري التحميل...',
    'common.or': 'أو',
    'common.retry': 'إعادة المحاولة',
    'units.feddan': 'فدان',
    'units.celsius': '°س',
    'units.percent': '٪',
    'units.kmh': 'كم/س',
    'app.name': 'أجري لينس',
    'app.tagline': 'مساعدك الزراعي الذكي',
    'onboarding.title1': 'اكتشف أمراض النباتات',
    'onboarding.desc1':
        'التقط صورة لنباتك واحصل على كشف مدعوم بالذكاء الاصطناعي.',
    'onboarding.title2': 'راقب حقولك',
    'onboarding.desc2': 'تابع صحة الحقول والمخاطر والسجل في مكان واحد.',
    'onboarding.title3': 'احصل على نصائح عملية',
    'onboarding.desc3': 'استخدم أجري بوت لفهم النتائج ونصائح الوقاية.',
    'onboarding.skip': 'تخطي',
    'onboarding.getStarted': 'ابدأ الآن',
    'language.title': 'اختر لغتك',
    'language.subtitle': 'اختر اللغة المفضلة',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.continue': 'متابعة',
    'login.title': 'مرحباً بعودتك!',
    'login.subtitle': 'أدخل رقم هاتفك للمتابعة',
    'login.phone': 'رقم الهاتف',
    'login.phonePlaceholder': '01234567890',
    'login.sendOTP': 'إرسال الكود',
    'login.otpTitle': 'أدخل كود التحقق',
    'login.otpSubtitle': 'أرسلنا كوداً إلى',
    'login.verify': 'تحقق',
    'login.resend': 'إعادة إرسال الكود',
    'login.successTitle': 'أهلاً بك!',
    'login.successMessage': 'تم تسجيل الدخول بنجاح',
    'home.goodMorning': 'صباح الخير',
    'home.goodAfternoon': 'مساء الخير',
    'home.goodEvening': 'مساء النور',
    'home.goodNight': 'تصبح على خير',
    'home.farmer': 'المزارع',
    'home.plantHealth': 'صحة النباتات اليوم',
    'home.healthyStatus': 'حالة صحية جيدة عبر حقولك',
    'home.quickScan': 'فحص سريع',
    'home.quickScanDesc': 'اكتشف الأمراض فوراً',
    'home.activeAlerts': 'التنبيهات النشطة',
    'home.alerts': 'التنبيهات',
    'home.viewAll': 'عرض الكل',
    'home.moderateRisk': 'تم اكتشاف خطر متوسط',
    'home.treatmentComplete': 'اكتمل العلاج',
    'home.weatherToday': 'الطقس اليوم',
    'home.partlyCloudy': 'غائم جزئياً',
    'home.humidity': 'الرطوبة',
    'home.wind': 'الرياح',
    'home.temp': 'الحرارة',
    'home.myFields': 'حقولي',
    'home.forecasting': 'التوقعات',
    'fields.title': 'حقولي',
    'fields.viewMap': 'عرض الخريطة',
    'fields.addNew': 'إضافة حقل جديد',
    'fields.healthy': 'صحي',
    'fields.warning': 'تحذير',
    'fields.area': 'المساحة',
    'fields.healthScore': 'درجة الصحة',
    'fields.overview': 'نظرة عامة',
    'fields.totalArea': 'المساحة الإجمالية',
    'fields.avgHealth': 'متوسط الصحة',
    'fields.riskDetected': 'تم اكتشاف مناطق خطر متوسطة',
    'fields.fieldName': 'الحقل أ',
    'fields.location': 'الموقع',
    'fields.cropType': 'نوع المحصول',
    'fields.soilType': 'نوع التربة',
    'fields.irrigationType': 'نظام الري',
    'fields.editField': 'تعديل الحقل',
    'fields.riskLevel': 'مستوى الخطر',
    'fields.health': 'الصحة',
    'fields.alerts': 'التنبيهات',
    'fields.totalFields': 'إجمالي الحقول',
    'addField.title': 'إضافة حقل جديد',
    'addField.editTitle': 'تعديل الحقل',
    'addField.infoBanner': 'سجل حقلك لتفعيل مراقبة الأمراض والتوقعات.',
    'addField.editInfoBanner':
        'حدّث معلومات حقلك للحفاظ على دقة بيانات المتابعة.',
    'addField.name': 'اسم الحقل',
    'addField.namePlaceholder': 'مثال: الحقل أ، المزرعة الشمالية',
    'addField.location': 'الموقع',
    'addField.locationPlaceholder': 'مثال: القسم الشمالي، اسم القرية',
    'addField.markOnMap': 'تحديد على الخريطة',
    'addField.area': 'المساحة (بالفدان)',
    'addField.areaPlaceholder': 'مثال: 2.5',
    'addField.cropType': 'نوع المحصول',
    'addField.selectCrop': 'اختر نوع المحصول',
    'addField.soilType': 'نوع التربة',
    'addField.selectSoil': 'اختر نوع التربة',
    'addField.irrigation': 'نظام الري',
    'addField.selectIrrigation': 'اختر نظام الري',
    'addField.photo': 'صورة الحقل (اختياري)',
    'addField.takePhoto': 'التقط أو ارفع صورة',
    'addField.updatePhoto': 'تحديث الصورة',
    'addField.submit': 'إضافة الحقل',
    'addField.update': 'حفظ التغييرات',
    'addField.successTitle': 'تمت إضافة الحقل بنجاح!',
    'addField.successMessage': 'تم تسجيل حقلك الجديد',
    'addField.updateSuccessTitle': 'تم تحديث الحقل بنجاح!',
    'addField.updateSuccessMessage': 'تم حفظ التغييرات',
    'addField.deleteTitle': 'حذف الحقل؟',
    'addField.deleteMessage':
        'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع بيانات الحقل نهائياً.',
    'addField.confirmDelete': 'نعم، احذف الحقل',
    'addField.required': 'مطلوب',
    'crops.wheat': 'قمح',
    'crops.rice': 'أرز',
    'crops.corn': 'ذرة',
    'crops.tomato': 'طماطم',
    'crops.tomatoes': 'طماطم',
    'crops.potato': 'بطاطس',
    'crops.potatoes': 'بطاطس',
    'crops.apple': 'تفاح',
    'crops.apples': 'تفاح',
    'crops.grape': 'عنب',
    'crops.mushroom': 'فطر',
    'crops.sugarCane': 'قصب السكر',
    'crops.sweetPotato': 'بطاطا حلوة',
    'crops.cotton': 'قطن',
    'crops.onion': 'بصل',
    'crops.onions': 'بصل',
    'crops.cucumber': 'خيار',
    'crops.pepper': 'فلفل',
    'crops.eggplant': 'باذنجان',
    'crops.bean': 'فول',
    'crops.beans': 'فول',
    'crops.barley': 'شعير',
    'crops.other': 'أخرى',
    'soil.clay': 'طينية',
    'soil.sandy': 'رملية',
    'soil.loamy': 'طميية',
    'soil.silty': 'غرينية',
    'soil.peaty': 'خثية',
    'soil.chalky': 'جيرية',
    'irrigation.drip': 'ري بالتنقيط',
    'irrigation.sprinkler': 'ري بالرش',
    'irrigation.surface': 'ري سطحي/غمر',
    'irrigation.manual': 'ري يدوي',
    'irrigation.rainfed': 'ري مطري',
    'scan.title': 'فحص النبات',
    'scan.instruction': 'وجه الكاميرا نحو الورقة أو النبات المصاب',
    'scan.tips': 'نصائح لأفضل النتائج:',
    'scan.tip1': 'استخدم إضاءة جيدة',
    'scan.tip2': 'اقترب من الورقة',
    'scan.tip3': 'حافظ على ثبات الكاميرا',
    'scan.tip4': 'ركز على المنطقة المصابة',
    'scan.capture': 'التقط صورة',
    'scan.gallery': 'اختر من المعرض',
    'scan.analyzing': 'جاري تحليل النبات...',
    'scan.photoMode': 'وضع الصورة',
    'scan.videoMode': 'وضع الفيديو',
    'scan.videoInstruction': 'تسجيل فيديو لمناطق النبات المصاب',
    'scan.videoTip': 'أقصى 30 ثانية - عرض زوايا متعددة',
    'scan.resultTitle': 'نتيجة الفحص',
    'scan.confidence': 'دقة التشخيص',
    'scan.severity': 'الخطورة',
    'scan.viewDetails': 'عرض التفاصيل الكاملة',
    'scan.scanAnother': 'فحص نبات آخر',
    'scan.saveToField': 'حفظ للحقل',
    'scan.selectCrop': 'اختر محصولك',
    'scan.selectCropDesc': 'اختر المحصول الذي تريد فحصه للحصول على دقة أعلى',
    'scan.comingSoon': 'قريباً',
    'scan.cropComingSoon':
        'فحص {crop} سيكون متاحاً قريباً. يمكنك إضافته إلى الحقول الآن.',
    'scan.noResults': 'لم يتم اكتشاف أي أمراض',
    'scan.healthy': 'يبدو النبات صحياً',
    'disease.overview': 'نظرة عامة',
    'disease.symptoms': 'الأعراض',
    'disease.treatment': 'العلاج',
    'disease.prevention': 'الوقاية',
    'disease.affectedArea': 'المنطقة المصابة',
    'disease.detectionDate': 'تاريخ الاكتشاف',
    'disease.recommendedAction': 'الإجراء الموصى به',
    'disease.urgency': 'الاستعجال',
    'disease.high': 'عالي',
    'disease.medium': 'متوسط',
    'disease.low': 'منخفض',
    'chat.title': 'مساعد أجري بوت',
    'chat.subtitle': 'دائماً هنا للمساعدة',
    'chat.placeholder': 'اسألني أي شيء...',
    'chat.greeting': 'مرحباً! أنا أجري بوت. كيف يمكنني مساعدتك اليوم؟',
    'chat.tryAsking': 'جرّب أن تسأل:',
    'chat.question1': 'ما هي الأمراض التي تصيب الطماطم؟',
    'chat.question2': 'كيف أمنع اللفحة؟',
    'chat.question3': 'ما أفضل سماد للقمح؟',
    'chat.question4': 'متى أروي المحاصيل؟',
    'chat.buttonTooltip': 'التحدث مع أجري بوت',
    'forecast.title': 'توقعات الأمراض',
    'forecast.currentRisk': 'مستوى الخطر الحالي',
    'forecast.riskTrend': 'اتجاه الخطر لمدة 7 أيام',
    'forecast.lowRisk': 'خطر منخفض',
    'forecast.moderateRisk': 'خطر متوسط',
    'forecast.highRisk': 'خطر عالي',
    'forecast.weatherImpact': 'تأثير الطقس',
    'forecast.favorableConditions': 'ظروف مواتية لانتشار الأمراض',
    'forecast.upcomingAlerts': 'التنبيهات القادمة',
    'reports.title': 'التقارير',
    'reports.generate': 'إنشاء تقرير جديد',
    'reports.monthly': 'ملخص شهري',
    'reports.seasonal': 'تحليل موسمي',
    'reports.download': 'تحميل PDF',
    'reports.share': 'مشاركة التقرير',
    'reports.noReports': 'لا توجد تقارير بعد',
    'reports.createFirst': 'أنشئ أول تقرير لرؤية التفاصيل',
    'notifications.title': 'الإشعارات',
    'notifications.markAllRead': 'وضع علامة مقروء للكل',
    'notifications.today': 'اليوم',
    'notifications.yesterday': 'أمس',
    'notifications.earlier': 'سابقاً',
    'profile.title': 'الملف الشخصي',
    'profile.editProfile': 'تعديل الملف',
    'profile.accountSettings': 'إعدادات الحساب',
    'profile.subscription': 'خطة الاشتراك',
    'profile.helpSupport': 'المساعدة والدعم',
    'profile.about': 'عن أجري لينس',
    'profile.logout': 'تسجيل الخروج',
    'settings.title': 'الإعدادات',
    'settings.account': 'الحساب',
    'settings.editProfile': 'تعديل الملف',
    'settings.phoneNumber': 'رقم الهاتف',
    'settings.email': 'البريد الإلكتروني',
    'settings.preferences': 'التفضيلات',
    'settings.language': 'اللغة',
    'settings.notifications': 'الإشعارات',
    'settings.units': 'الوحدات',
    'settings.privacy': 'الخصوصية والأمان',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.dataPrivacy': 'خصوصية البيانات',
    'settings.termsConditions': 'الشروط والأحكام',
    'settings.help': 'المساعدة والدعم',
    'settings.tutorial': 'دليل التطبيق',
    'settings.contactSupport': 'اتصل بالدعم',
    'settings.faq': 'الأسئلة الشائعة',
    'subscription.title': 'الاشتراك',
    'subscription.currentPlan': 'الخطة الحالية',
    'subscription.upgrade': 'ترقية الخطة',
    'subscription.free': 'الخطة المجانية',
    'subscription.basic': 'الخطة الأساسية',
    'subscription.standard': 'الخطة القياسية',
    'subscription.premium': 'الخطة المميزة',
    'subscription.choosePlan': 'اختر خطتك',
    'subscription.month': '/شهر',
    'subscription.selectPlan': 'اختر الخطة',
    'subscription.confirmPayment': 'تأكيد الدفع',
    'subscription.paymentMethod': 'طريقة الدفع',
    'subscription.success': 'تم تفعيل الاشتراك!',
    'subscription.current': 'الخطة الحالية',
    'subscription.pro': 'خطة احترافية',
    'subscription.enterprise': 'خطة مؤسسات',
    'subscription.cardNumber': 'رقم البطاقة',
    'subscription.expiry': 'تاريخ الانتهاء',
    'subscription.cvv': 'CVV',
    'subscription.pay': 'ادفع الآن',
    'subscription.confirmTitle': 'تم الدفع بنجاح!',
    'subscription.confirmMessage': 'تم تفعيل اشتراكك بنجاح.',
    'subscription.manage': 'إدارة الاشتراك',
    'subscription.cancelPlan': 'إلغاء الخطة',
    'subscription.renewDate': 'تاريخ التجديد',
    'subscription.usage': 'استخدام هذا الشهر',
    'subscription.trialActive': 'تجربة مجانية',
    'subscription.trialDaysLeft': 'أيام متبقية في تجربتك المجانية',
    'subscription.trialExpiredTitle': 'انتهت الفترة التجريبية',
    'subscription.trialExpiredBody': 'انتهت فترة التجربة المجانية لمدة أسبوع. اختر خطة للاستمرار في استخدام AgriLens.',
    'subscription.choosePlanBtn': 'اختر خطة',
    'subscription.payment': 'الدفع',
    'subscription.orderSummary': 'ملخص الطلب',
    'subscription.total': 'الإجمالي',
    'subscription.selectPayment': 'اختر طريقة الدفع',
    'subscription.card': 'بطاقة ائتمان / خصم',
    'subscription.vodafoneCash': 'فودافون كاش',
    'subscription.fawry': 'فوري',
    'subscription.instaPay': 'إنستاباي',
    'subscription.holderName': 'اسم حامل البطاقة',
    'subscription.mobileNumber': 'رقم الهاتف',
    'subscription.fawryCode': 'كود فوري الخاص بك',
    'subscription.bankName': 'اختر البنك',
    'subscription.accountNumber': 'رقم الحساب / IBAN',
    'subscription.processing': 'جارٍ معالجة الدفع...',
    'subscription.receiptSent': 'تم إرسال إيصال الدفع إلى رقم هاتفك المسجل.',
    'nav.home': 'الرئيسية',
    'nav.scan': 'فحص',
    'nav.fields': 'الحقول',
    'nav.forum': 'المنتدى',
    'nav.reports': 'التقارير',
    'nav.profile': 'الملف',
    'registration.title': 'إنشاء ملفك الشخصي',
    'registration.subtitle': 'أخبرنا قليلاً عن نفسك',
    'registration.fullName': 'الاسم الكامل',
    'registration.namePlaceholder': 'أدخل اسمك الكامل',
    'registration.country': 'الدولة',
    'registration.selectCountry': 'اختر بلدك',
    'registration.egypt': 'مصر',
    'registration.saudiArabia': 'السعودية',
    'registration.uae': 'الإمارات',
    'registration.jordan': 'الأردن',
    'registration.profilePhoto': 'صورة الملف الشخصي (اختياري)',
    'registration.uploadPhoto': 'تحميل الصورة',
    'registration.changePhoto': 'تغيير الصورة',
    'registration.continue': 'متابعة',
    'editProfile.title': 'تعديل الملف الشخصي',
    'editProfile.subtitle': 'تحديث معلوماتك',
    'editProfile.name': 'الاسم الكامل',
    'editProfile.email': 'البريد الإلكتروني',
    'editProfile.emailPlaceholder': 'بريدك الإلكتروني',
    'editProfile.phone': 'رقم الهاتف',
    'editProfile.country': 'الدولة',
    'editProfile.photo': 'صورة الملف الشخصي',
    'editProfile.saveChanges': 'حفظ التغييرات',
    'editProfile.successTitle': 'تم تحديث الملف!',
    'editProfile.successMessage': 'تم تحديث ملفك الشخصي بنجاح',
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'اعثر على إجابات لأسئلتك الشائعة',
    'faq.q1': 'كيف يعمل كشف الأمراض؟',
    'faq.a1':
        'يحلل أجري لينس صور النبات ويعرض المرض المتوقع ومستوى الثقة والخطورة والتوصيات.',
    'faq.q2': 'ما مدى دقة كشف الأمراض؟',
    'faq.a2':
        'تعتمد الدقة على تغطية المحصول وجودة الصورة. استخدم مستوى الثقة وراجع المختص في الحالات الحرجة.',
    'faq.q3': 'هل يمكنني استخدام أجري لينس دون اتصال؟',
    'faq.a3': 'يمكن للتطبيق حفظ الفحوصات محلياً ثم إرسالها عند عودة الاتصال.',
    'faq.q4': 'ما المحاصيل المدعومة؟',
    'faq.a4':
        'يركز هذا الإصدار على الطماطم والذرة والقمح والبطاطا الحلوة، مع إضافة محاصيل أخرى لاحقاً.',
    'faq.q5': 'كيف أضيف عدة حقول؟',
    'faq.a5': 'اذهب إلى حقولي واضغط إضافة حقل جديد ثم أدخل التفاصيل.',
    'faq.q6': 'ماذا تُظهر التوقعات؟',
    'faq.a6':
        'تجمع التوقعات بين الفحوصات الحديثة والطقس لتقدير خطر المرض على المدى القصير.',
    'terms.title': 'الشروط والأحكام',
    'terms.subtitle': 'آخر تحديث: مارس 2026',
    'privacy.title': 'سياسة خصوصية البيانات',
    'privacy.subtitle': 'كيف نحمي معلوماتك',
    'support.title': 'اتصل بالدعم',
    'support.subtitle': 'نحن هنا للمساعدة',
    'support.email': 'راسلنا',
    'support.emailAddress': 'support@agrilens.app',
    'support.phone': 'اتصل بنا',
    'support.phoneNumber': '+20 123 456 7890',
    'support.hours': 'ساعات الدعم',
    'support.hoursTime': 'الأحد - الخميس: 9 صباحاً - 6 مساءً',
    'support.sendMessage': 'إرسال رسالة',
    'support.name': 'اسمك',
    'support.emailLabel': 'بريدك الإلكتروني',
    'support.subject': 'الموضوع',
    'support.message': 'الرسالة',
    'support.messagePlaceholder': 'صف مشكلتك أو سؤالك...',
    'support.submit': 'إرسال الرسالة',
    'support.successTitle': 'تم إرسال الرسالة!',
    'support.successMessage': 'سنرد عليك خلال 24 ساعة',
    'tutorial.title': 'دليل التطبيق',
    'tutorial.subtitle': 'تعلّم كيفية استخدام أجري لينس',
    'tutorial.step1Title': 'فحص النباتات',
    'tutorial.step1': 'التقط صورة واضحة للجزء المصاب من النبات.',
    'tutorial.step2Title': 'عرض النتائج',
    'tutorial.step2': 'راجع توقع المرض ومستوى الثقة والخطورة والتوصيات.',
    'tutorial.step3Title': 'إدارة الحقول',
    'tutorial.step3': 'أضف حقولك وحدّث بيانات المحصول والري باستمرار.',
    'tutorial.step4Title': 'فحص التوقعات',
    'tutorial.step4': 'اعرض خطر المرض قصير المدى بناءً على الفحوصات والطقس.',
    'tutorial.step5Title': 'مراجعة التقارير',
    'tutorial.step5': 'أنشئ تقارير لسجل الفحوصات ومتابعة الحقول.',
    'tutorial.step6Title': 'اسأل أجري بوت',
    'tutorial.step6': 'استخدم المساعد لشرح النتائج وتقديم نصائح الوقاية.',
    'tutorial.watchVideo': 'مشاهدة الدليل المرئي',
    'tutorial.restart': 'إعادة تشغيل الدليل',
    'privacy.intro': 'خصوصيتك تهمنا. لا يجمع أجري لينس إلا ما هو ضروري لتقديم خدمات كشف الأمراض ومراقبة الحقول والتقارير. لا نبيع بياناتك أبداً.',
    'privacy.section1Title': 'ما الذي نجمعه',
    'privacy.section1': 'نجمع صور النباتات التي ترفعها، ونتائج الفحوصات، وتفاصيل الحقول (الاسم، الموقع، نوع المحصول)، وأنماط الاستخدام الأساسية. لا يتم جمع أي بيانات مالية شخصية.',
    'privacy.section2Title': 'كيف نستخدم بياناتك',
    'privacy.section2': 'تُستخدم بياناتك لتشغيل كشف الأمراض بالذكاء الاصطناعي، وتقارير صحة الحقول، والتوقعات. قد تُستخدم الأنماط المجمعة والمجهولة الهوية لتحسين دقة النموذج.',
    'privacy.section3Title': 'تخزين البيانات والأمان',
    'privacy.section3': 'جميع البيانات مشفرة أثناء النقل (TLS) وأثناء التخزين. تُحفظ الصور على خوادم آمنة، والوصول مقتصر على أنظمة أجري لينس المعتمدة فقط.',
    'privacy.section4Title': 'حقوقك',
    'privacy.section4': 'يمكنك عرض بياناتك أو تصديرها أو حذفها نهائياً في أي وقت عبر إعدادات الحساب أو بالتواصل مع support@agrilens.app. سنتعامل مع طلبك خلال 7 أيام.',
    'privacy.section5Title': 'المشاركة مع أطراف ثالثة',
    'privacy.section5': 'لا نبيع بياناتك ولا نؤجرها. نشارك البيانات فقط مع مزودي خدمات موثوقين (استضافة سحابية، تحليلات) وفق اتفاقيات معالجة بيانات صارمة.',
    'privacy.section6Title': 'التواصل والتحديثات',
    'privacy.section6': 'لأي استفسار يتعلق بالخصوصية، راسلنا على support@agrilens.app. قد نحدّث هذه السياسة بشكل دوري؛ واستمرارك في استخدام التطبيق يُعدّ قبولاً للتغييرات.',
    'terms.intro': 'يرجى قراءة هذه الشروط بعناية قبل استخدام أجري لينس. بإنشاء حساب أو استخدام التطبيق فإنك توافق على الالتزام بها.',
    'terms.section1Title': 'قبول الشروط',
    'terms.section1': 'باستخدامك لأجري لينس تؤكد أن عمرك 18 عاماً على الأقل وأنك توافق على هذه الشروط والأحكام. إذا كنت لا توافق على أي جزء منها، يرجى التوقف عن استخدام التطبيق.',
    'terms.section2Title': 'استخدام الخدمة',
    'terms.section2': 'أجري لينس مقدَّم لأغراض المراقبة الزراعية وكشف أمراض النباتات. توافق على عدم إساءة استخدام الخدمة أو الهندسة العكسية للتطبيق أو محاولة الوصول غير المصرح به.',
    'terms.section3Title': 'إخلاء مسؤولية الكشف عن الأمراض',
    'terms.section3': 'جميع نتائج الكشف هي تقديرات مدعومة بالذكاء الاصطناعي وليست بديلاً عن المشورة الزراعية المتخصصة. استشر دائماً مختصاً مؤهلاً في القرارات الحرجة.',
    'terms.section4Title': 'مسؤولية الحساب والبيانات',
    'terms.section4': 'أنت مسؤول عن الحفاظ على أمان بيانات تسجيل الدخول وجميع الأنشطة التي تتم من خلال حسابك. أبلغنا فوراً على support@agrilens.app في حال اشتبهت بوصول غير مصرح به.',
    'terms.section5Title': 'الملكية الفكرية',
    'terms.section5': 'جميع نماذج الذكاء الاصطناعي والتصاميم والعلامات التجارية والبرامج في أجري لينس مملوكة أو مرخصة لنا. يُحظر النسخ أو التوزيع أو الاستخدام التجاري غير المرخص.',
    'terms.section6Title': 'التعديلات والإنهاء',
    'terms.section6': 'يحق لنا تحديث هذه الشروط أو تعليق الحسابات المخالفة في أي وقت. استمرارك في استخدام التطبيق بعد أي تحديث يُعدّ قبولاً للشروط الجديدة.',
  },
};
